### ISSUE TITLE
uploading file fails in test

### ISSUE THREAD

**Issue by grrrisu** [grrrisu/zero-rails#249]
uploading the avatar for a user works fine, but in the test it fails.

```ruby
    avatar_image = fixture_file_upload(Rails.root.join('test', 'fixtures', 'files', 'jon.snow.png'), 'image/png')
    put admin_user_path(users(:jon_snow), params: {
      user:{
        email: 'jonny.snow@example.com',
        avatar: avatar_image
      }
    })
```

```
r test test/integration/admin/users_controller_test.rb:57
Run options: --seed 52027

# Running:

E

Error:
Admin::UsersControllerTest#test_a_user_can_edit_himself:
ActiveSupport::MessageVerifier::InvalidSignature: ActiveSupport::MessageVerifier::InvalidSignature
    app/controllers/admin/users_controller.rb:36:in `update'
    test/integration/admin/users_controller_test.rb:58:in `block in <class:UsersControllerTest>'


rails test test/integration/admin/users_controller_test.rb:50
```

remove the avatar parameter and test will work (current state)

**Comment by lipanski** [comment]
I just randomly found this issue while searching for a solution to the same problem. Figures out the fix is pretty easy:

```ruby
 put admin_user_path(users(:jon_snow)), params: {
      user:{
        email: 'jonny.snow@example.com',
        avatar: avatar_image
      }
    }
```

If the `params` are set as arugments of the `_path` method call (instead of the `put` method call), you get query parameters - which don't play nice with file uploads.

**Comment by grrrisu** [comment]
@lipanski yes, of course! Thank you very much, for reporting!
